### ISSUE TITLE
v0.1.4 being offered on CKAN for 1.2

### ISSUE THREAD

**Issue by ericfriesen** [linuxgurugamer/RetractableLiftingSurface#1]
Hi, forgive me if posting in the wrong place.
It seems v0.1.4 is being offered on CKAN for 1.2.x, where I believe it should be 0.1.3 max according to your RetractableLiftingSurface.version
Please point me in the right direction if I should be posting elsewhere, thank you!

**Comment by linuxgurugamer** [comment]
Thank you for the notice, i'll look into it

**Comment by linuxgurugamer** [comment]
It's been fixed, thank you
