### ISSUE TITLE
ModuleControlSurface, ignorePitch not not functioning correctly

### ISSUE THREAD

**Issue by steedcrugeon** [linuxgurugamer/RetractableLiftingSurface#2]
Using RetractableLiftingSurface with ModuleControlSurface in the config shown here:
[OTAV Starboard Deployable Wing](https://github.com/steedcrugeon/REKT/blob/steedcrugeon-patch-1/SHED/Parts/OTAV/OTAVmain/OTAVwingletStbd.cfg)
The "ignorePitch = True" is not carrying through from the ModuleControlSurface into the ModuleRetractableLiftingSurface.
This doesn't affect its ability to be deactivated in game so 'Pitch' can still be turned off by the player, in the VAB or in-flight.

This behaviour was observed on Windows x64 machine for the current KSPx64, 1.3.0 version of the game using RetractableLifitngSurface Version 1.4

**Comment by linuxgurugamer** [comment]
Can you elaborate, a video, perhaps

**Comment by steedcrugeon** [comment]
Fresh KSP 1.3 Install removed issue. Suspect local KSP install where problem occurred was corrupted.
