### ISSUE TITLE
CKAN data is installing v0.1.4 (for KSP 1.3) in a KSP 1.2.2 install

### ISSUE THREAD

**Issue by Dunbaratu** [linuxgurugamer/RetractableLiftingSurface#3]
This usually indicates some version numbers somewhere in the config file for the project aren't right.

When playing a KSP 1.2.2 install, I shouldn't be getting ZIP's for a KSP 1.3-compiled mod installed.  (They can cause it to be unable to load the game).

**Comment by linuxgurugamer** [comment]
yes, there is a problem, I'll ge tit fixed.
But, I don't think you will have any issues with thi

**Comment by linuxgurugamer** [comment]
Should be fixed, was some old stale data in the CKAN which came back.
