### ISSUE TITLE
NullReferenceException on OnStart @1.4.1 MacOS

### ISSUE THREAD

**Issue by Lisias** [linuxgurugamer/RetractableLiftingSurface#4]
When the user clicks on the Part from the Menu to add to a vessel, a exception **NullReferenceException** happens on OnStart and is logged. The part attaches to the craft, but the functionality is incomplete (TweakScale didn't worker, I'm presuming it's due being later on the calling chain).

Interesting files attached:

* KSP.log
* Player.log (Unity)
* Part.cfg known to reproduce the problem
[KSP.log](https://github.com/linuxgurugamer/RetractableLiftingSurface/files/1962432/KSP.log)
[Player.log](https://github.com/linuxgurugamer/RetractableLiftingSurface/files/1962430/Player.log)
[my-crashing-winglet.cfg.txt](https://github.com/linuxgurugamer/RetractableLiftingSurface/files/1962434/my-crashing-winglet.cfg.txt)

**Comment by linuxgurugamer** [comment]
What mod, what part?

**Comment by linuxgurugamer** [comment]
This isn't a bug.  This mod is for RETRACTABLE surfaces, which means there must be an animation in the part.  You are using:
Squad/Parts/Aero/wingletDeltaDeluxe/model
which doesn't have any animations.  The only animation is the control surface, which doesn't apply

**Comment by linuxgurugamer** [comment]
I've added an error message if no deploy animation is found
